[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.12"

[dependencies]
risc0-zkvm = { version = "0.14", default-features = false }
ting-tong-core = {path = "../ting-tong-core", version = "1.0.0" }
rand = "0.8"
