[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = "0.14.0"
serde = "1.0"
ting-tong-core = { path = "../core" }
rand = "0.8.5"
